/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coordinatorlayout;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f04002b;
        public static final int coordinatorLayoutStyle = 0x7f0400ac;
        public static final int font = 0x7f0400ec;
        public static final int fontProviderAuthority = 0x7f0400ee;
        public static final int fontProviderCerts = 0x7f0400ef;
        public static final int fontProviderFetchStrategy = 0x7f0400f0;
        public static final int fontProviderFetchTimeout = 0x7f0400f1;
        public static final int fontProviderPackage = 0x7f0400f2;
        public static final int fontProviderQuery = 0x7f0400f3;
        public static final int fontStyle = 0x7f0400f4;
        public static final int fontVariationSettings = 0x7f0400f5;
        public static final int fontWeight = 0x7f0400f6;
        public static final int keylines = 0x7f040128;
        public static final int layout_anchor = 0x7f04012d;
        public static final int layout_anchorGravity = 0x7f04012e;
        public static final int layout_behavior = 0x7f04012f;
        public static final int layout_dodgeInsetEdges = 0x7f04015b;
        public static final int layout_insetEdge = 0x7f040164;
        public static final int layout_keyline = 0x7f040165;
        public static final int statusBarBackground = 0x7f0401df;
        public static final int ttcIndex = 0x7f040248;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f06008e;
        public static final int notification_icon_bg_color = 0x7f06008f;
        public static final int ripple_material_light = 0x7f06009b;
        public static final int secondary_text_default_material_light = 0x7f06009d;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070052;
        public static final int compat_button_inset_vertical_material = 0x7f070053;
        public static final int compat_button_padding_horizontal_material = 0x7f070054;
        public static final int compat_button_padding_vertical_material = 0x7f070055;
        public static final int compat_control_corner_material = 0x7f070056;
        public static final int compat_notification_large_icon_max_height = 0x7f070057;
        public static final int compat_notification_large_icon_max_width = 0x7f070058;
        public static final int notification_action_icon_size = 0x7f0700c4;
        public static final int notification_action_text_size = 0x7f0700c5;
        public static final int notification_big_circle_margin = 0x7f0700c6;
        public static final int notification_content_margin_start = 0x7f0700c7;
        public static final int notification_large_icon_height = 0x7f0700c8;
        public static final int notification_large_icon_width = 0x7f0700c9;
        public static final int notification_main_column_padding_top = 0x7f0700ca;
        public static final int notification_media_narrow_margin = 0x7f0700cb;
        public static final int notification_right_icon_size = 0x7f0700cc;
        public static final int notification_right_side_padding_top = 0x7f0700cd;
        public static final int notification_small_icon_background_padding = 0x7f0700ce;
        public static final int notification_small_icon_size_as_large = 0x7f0700cf;
        public static final int notification_subtext_size = 0x7f0700d0;
        public static final int notification_top_pad = 0x7f0700d1;
        public static final int notification_top_pad_large_text = 0x7f0700d2;
    }
    public static final class drawable {
        private drawable() {}

        public static final int notification_action_background = 0x7f080096;
        public static final int notification_bg = 0x7f080097;
        public static final int notification_bg_low = 0x7f080098;
        public static final int notification_bg_low_normal = 0x7f080099;
        public static final int notification_bg_low_pressed = 0x7f08009a;
        public static final int notification_bg_normal = 0x7f08009b;
        public static final int notification_bg_normal_pressed = 0x7f08009c;
        public static final int notification_icon_background = 0x7f08009d;
        public static final int notification_template_icon_bg = 0x7f08009e;
        public static final int notification_template_icon_low_bg = 0x7f08009f;
        public static final int notification_tile_bg = 0x7f0800a0;
        public static final int notify_panel_notification_icon_bg = 0x7f0800a1;
    }
    public static final class id {
        private id() {}

        public static final int action_container = 0x7f0a0016;
        public static final int action_divider = 0x7f0a0018;
        public static final int action_image = 0x7f0a0019;
        public static final int action_text = 0x7f0a001f;
        public static final int actions = 0x7f0a0020;
        public static